version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    command: pnpm run start:dev
    volumes:
      - .:/app


  db:
    image: postgres:15
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backnest
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: